### ISSUE TITLE
difficulties in installing sentix

### ISSUE THREAD

**Issue by aseiff** [valeriobasile/sentixR#4]
I downloaded your package (many thanks, by the way), but am unable to install it with RStudio. I get the message: 
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’

* removing ‘/Users/Me/Desktop/Folder/renv/library/R-4.1/x86_64-apple-darwin17.0/sentix’

Something I can do?

**Comment by valeriobasile** [comment]
In version 3.6 or R, "staged installation" has been introduced. This in turn added checks on file paths that produce what I think are false positives such in this case. I am trying to get my head around it, probably I will have to rebuild the package (I'm not really a R expert, so a pull request would be welcome!).

In the meantime, installing with --no-staged-install seem to work just fine, as suggested by the error message:

R CMD INSTALL sentix_0.0.0.9000.tar.gz --no-staged-install

**Comment by aseiff** [comment]
Thanks a lot. But being just a beginner (two-months-course), I have to give up for now, and return to German and English ...

**Comment by valeriobasile** [comment]
Ok, I will close this now. I suggest to use a more friendly tool (e.g. Python with spacy_udpipe) to process natural language with a lexicon like Sentix, unless R is a specific constraint. This package (SentixR) was specifically built for people who needed R.
